import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import './globals.css'
import Home from './page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar/>
      {children}
      <Footer/>
      
    </>

  )
}
